# --- STARS ---

STARS_ELITE = 25
STARS_HIGH = 20
STARS_MEDIUM = 15
STARS_LOW = 10
STARS_MINIMAL = 5

# --- RELEVANCE ---

RELEVANCE_FULL_MATCH = 35

# --- ACTIVITY ---

ACTIVITY_REALLY_RECENT = 30
ACTIVITY_VERY_RECENT = 25
ACTIVITY_RECENT = 18
ACTIVITY_MODERATE = 10
ACTIVITY_LOW = 5

# --- PENALTIES ---

FORK_PENALTY = 5
INACTIVITY_PENALTY = 10
LOW_QUALITY_REPO_PENALTY = 10

# --- BONUS ---

RELEVANT_FORK_BONUS = 10
